### ISSUE TITLE
[Curricula Opening Page] Curricula Modules table alignment

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#131] opened 2019-11-14 23:14 UTC
[strong]
(Windows 10 using Chrome/Firefox/Edge)

When viewing the Curricula Modules table on the bottom of the page, the table flows off the right side of the page. Have to scroll horizontally to see the entire table.

**Comment by yatil** [comment] 2019-11-15 10:07
@slhenry and I talked about this in this issue on the Media Guide: https://github.com/w3c/wai-website/issues/565 

The current way, extending the scrolling page to the right and breaking out of the container was decided as the way we want to address huge tables.

It works as expected at this moment.

**Comment by shawna-slh** [comment] 2019-11-15 13:36
@slhenry thought that would only happen on small screens.

Will look at it....

**Comment by yatil** [comment] 2019-11-15 15:45
It happens when the viewport width is less than the table width.

**Comment by yatil** [comment] 2019-12-05 09:45
Duplicate of w3c/wai-media-guide#137

**Comment by daniel-montalvo** [comment] 2021-02-16 10:53
This seems to have been fixed after table simplification at https://wai-curricula.netlify.com/curricula/

**Closed as completed by daniel-montalvo** 2021-02-16 10:53 UTC
Labels: wontfix
