### ISSUE TITLE
Include relevant guidelines to each 'Topics to teach' section

### ISSUE THREAD

**Issue by PoornimaSubramanian** [w3c/wai-curricula#470] opened 2022-02-16 04:14 UTC
Include relevant WCAG guidelines / techniques links to each 'Topics to teach' section for intuitive learning. 

Note: This suggestion is for all the design modules (visual design, information design, etc.)

**Comment by daniel-montalvo** [comment] 2022-03-14 12:50
Thanks for your feedback @PoornimaSubramanian

We will consider this for future iteration. We are now working on the [Content Author modules](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/)

**Comment by daniel-montalvo** [comment] 2022-03-14 12:57
Closing. Duplicate of w3c/wai-website#710

**Closed as completed by daniel-montalvo** 2022-03-14 12:57 UTC
Labels: Future iteration
